// Three south-to-north campaign boards. Coordinates use (column, row), with row 0 at north.
export const CAMPAIGN_MAPS = [
 {id:'campaign-road',layout:['GGGGGGGGGGGG','GGGGGKGGGGGG','FFGGGGGGGGFF','FFGGGGGGGGFF','FFGGGGGGGGFF','FFGGGRRGGGFF','GGGGGVGGGGGG','GGGGGRRGGGGG','GGGGGRRGGGGG','GGGGGRRGGGGG','GGGGGRRGGGGG','GGGGGVGGGGGG','GGGGGRRGGGGG','FFGGGRRGGFFF','FFGGGGGGGGFF','FFGGGGGGGGFF','GGGGGCGGGGGG','GGGGGGGGGGGG'],hills:[[1,2],[2,2],[9,14],[10,14]]},
 {id:'campaign-woodland',layout:['GGGGGGGGGGGG','GGGGGKGGGGGG','FFFGGGGGGFFF','FFFGGGGGGFFF','FFFGGGGGGFFF','FFFGGGGGGFFF','GGGGGVGGGGGG','FFFGGGGGGFFF','FFFGGGGGGFFF','FFFGGGGGGFFF','FFFGGGGGGFFF','GGGGGVGGGGGG','FFFGGGGGGFFF','FFFGGGGGGFFF','FFFGGGGGGFFF','FFFGGGGGGFFF','GGGGGCGGGGGG','GGGGGGGGGGGG'],hills:[[1,2],[2,3],[9,3],[10,2],[1,13],[2,14],[9,14],[10,13]]},
 {id:'campaign-crossing',layout:['GGGGGGGGGGGG','GGGGGKGGGGGG','GGFFGGGGFFGG','GGFFGGGGFFGG','GGFFGGGGFFGG','GGGGGRRGGGGG','GGGGGVGGGGGG','GGGGGRRGGGGG','GGGWWBWWGGGG','GGGWWBWWGGGG','GGGWWBWWGGGG','GGGGGVGGGGGG','GGGGGRRGGGGG','GGFFGGGGFFGG','GGFFGGGGFFGG','GGFFGGGGFFGG','GGGGGCGGGGGG','GGGGGGGGGGGG'],hills:[[2,3],[9,3],[2,14],[9,14]]},
];
export default CAMPAIGN_MAPS;
